---
name: 添加新项目
about: 向 Awesome Spatio-Temporal AI 列表中添加新的开源项目
title: "[ADD] 项目名称"
labels: enhancement
assignees: ''

---

## 项目信息

请提供以下信息：

- **项目名称**: 
- **GitHub URL**: 
- **项目描述** (英文):
- **所属分类**: 
  - Trajectory Prediction (轨迹预测)
  - Urban Computing (城市计算)
  - Geospatial Machine Learning (地理空间机器学习)
  - World Models & 3D Generation (世界模型与3D生成)
  - Spatio-Temporal API Services (时空API服务)
  - OSGeo Spatiotemporal Analysis (OSGeo时空分析)

- **技术栈** (可选):
- **Stars 数量** (可选):

## 检查清单

- [ ] 我确认这是开源项目
- [ ] 我确认项目与时空智能相关
- [ ] 我已测试链接可访问
- [ ] 我已阅读贡献指南

## 补充说明 (可选)

请说明为什么这个项目值得添加到列表中，以及它的独特之处。
