---
name: 更新现有信息
about: 更新列表中已有项目、会议或期刊的信息
title: "[UPDATE] 更新内容描述"
labels: bug
assignees: ''

---

## 要更新的内容

- **类型**: 
  - [ ] GitHub 项目
  - [ ] 学术会议
  - [ ] 学术期刊
  - [ ] 媒体渠道
  - [ ] 其他

- **名称**:

## 更新内容

请描述需要更新什么信息：

- **当前信息**:
- **正确信息**:
- **更新原因**:

## 检查清单

- [ ] 我已确认需要更新的内容
- [ ] 我提供了正确的更新信息
- [ ] 我有可靠的来源支持更新
