name: Link Check

on:
  push:
    branches:
      - master
    paths:
      - 'awesomelist/*.json'
      - 'scripts/linkcheck.py'
  schedule:
    - cron: '0 0 1 * *'  # 每月1日 00:00 UTC

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run link check
        run: |
          python scripts/linkcheck.py

      - name: Commit broken links report (optional)
        if: ${{ env.GITEE_TOKEN != '' }}
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git config user.name "gitee-ci"
          git config user.email "ci@gitee.com"
          git add reports/broken_links.json
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(ci): update broken links report"
            git push
          fi
