name: Generate Metrics

on:
  push:
    branches:
      - master
    paths:
      - 'awesomelist/*.json'
      - 'scripts/metrics.py'
  schedule:
    - cron: '0 0 * * 1'  # 每周一 00:00 UTC

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate metrics
        run: |
          python scripts/metrics.py

      - name: Commit reports (optional)
        if: ${{ env.GITEE_TOKEN != '' }}
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git config user.name "gitee-ci"
          git config user.email "ci@gitee.com"
          git add reports/*
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(ci): update metrics reports"
            git push
          fi
